/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inter.face;

import medi.flow.*;

import java.text.ParseException;
import java.util.List;

import static medi.flow.Main.getClinica;
import static medi.flow.Text.splitStringToList;
import static medi.flow.Text.timeFormat;

/**
 *
 * @author Luis
 */
public class ConsultaMedico extends javax.swing.JPanel {

    /**
     * Creates new form Consulta
     */

    int nSns;
    // Construtor da classe
    public ConsultaMedico(Consulta consulta) throws ParseException {
        initComponents(); // Inicializa os componentes da interface

        // Atributos escondidos da consulta
        this.nSns = consulta.getSnsPaciente();

        // Preenche os componentes da interface
        nomePaciente.setText(consulta.getNomePaciente() != null ? consulta.getNomePaciente() : "Não disponível");// Preenche o nome do paciente
        String horaFormtatada = timeFormat(consulta.getHora());// Formata a hora da consulta
        data.setText(consulta.getData() != null ? consulta.getData() : "Não disponível");// Preenche a data da consulta
        hora.setText(horaFormtatada);// Preenche a hora da consulta

        // Preenche a lista de motivos da consulta
        List<String> motivoList = splitStringToList(consulta.getMotivo());// Obtem a lista de motivos da consulta
        motivos.setListData(motivoList.toArray(new String[0]));// Preenche a lista de motivos da consulta
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        label = new javax.swing.JLabel();
        nomePaciente = new javax.swing.JLabel();
        dataHora = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        algo = new javax.swing.JLabel();
        fichaMedicaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        motivos = new javax.swing.JList<>();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 149, 218), 3, true));
        setMaximumSize(new java.awt.Dimension(900, 100));
        setMinimumSize(new java.awt.Dimension(900, 100));
        setPreferredSize(new java.awt.Dimension(900, 100));
        setLayout(new java.awt.GridBagLayout());

        label.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label.setText("Nome do paciente:");
        label.setMaximumSize(new java.awt.Dimension(120, 30));
        label.setMinimumSize(new java.awt.Dimension(120, 30));
        label.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(label, gridBagConstraints);

        nomePaciente.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        nomePaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nomePaciente.setText("xxxxxx");
        nomePaciente.setMaximumSize(new java.awt.Dimension(300, 30));
        nomePaciente.setMinimumSize(new java.awt.Dimension(300, 30));
        nomePaciente.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(nomePaciente, gridBagConstraints);

        dataHora.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        dataHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dataHora.setText("Data/Hora:");
        dataHora.setMaximumSize(new java.awt.Dimension(120, 30));
        dataHora.setMinimumSize(new java.awt.Dimension(120, 30));
        dataHora.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(dataHora, gridBagConstraints);

        data.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        data.setText("dd/mm/yyyy");
        data.setMaximumSize(new java.awt.Dimension(120, 30));
        data.setMinimumSize(new java.awt.Dimension(120, 30));
        data.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 200);
        add(data, gridBagConstraints);

        hora.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        hora.setText("hh/mm");
        hora.setMaximumSize(new java.awt.Dimension(120, 30));
        hora.setMinimumSize(new java.awt.Dimension(120, 30));
        hora.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        add(hora, gridBagConstraints);

        algo.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        algo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        algo.setText("Motivo da Consulta:");
        algo.setMaximumSize(new java.awt.Dimension(130, 30));
        algo.setMinimumSize(new java.awt.Dimension(130, 30));
        algo.setPreferredSize(new java.awt.Dimension(130, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(algo, gridBagConstraints);

        fichaMedicaButton.setBackground(new java.awt.Color(0, 132, 193));
        fichaMedicaButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        fichaMedicaButton.setForeground(new java.awt.Color(245, 245, 245));
        fichaMedicaButton.setText("Registo Clínico");
        fichaMedicaButton.setMaximumSize(new java.awt.Dimension(125, 35));
        fichaMedicaButton.setMinimumSize(new java.awt.Dimension(125, 35));
        fichaMedicaButton.setPreferredSize(new java.awt.Dimension(125, 35));
        fichaMedicaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichaMedicaButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        add(fichaMedicaButton, gridBagConstraints);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 60));
        jScrollPane1.setRequestFocusEnabled(false);

        motivos.setBackground(new java.awt.Color(242, 242, 242));
        motivos.setBorder(null);
        motivos.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        motivos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        motivos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        motivos.setFocusable(false);
        motivos.setOpaque(false);
        motivos.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(motivos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Botão para abrir a ficha medica do paciente
    private void fichaMedicaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichaMedicaButtonActionPerformed
        List<RegistoClinico> listaRegistrosClinico = getClinica().getRegistos();// Obtem a lista de registos clinicos
        for(RegistoClinico registoClinico : listaRegistrosClinico){// Percorre a lista de registos clinicos
            if(registoClinico.getNumeroSns() == nSns){// Se o registo clinico for do paciente da consulta
                RegistoClinicoPanel registoClinicoPanel = new RegistoClinicoPanel(registoClinico);// Cria um painel com o registo clinico
                registoClinicoPanel.setVisible(true);// Torna o painel visivel
            }
        }
    }//GEN-LAST:event_fichaMedicaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel algo;
    private javax.swing.JLabel data;
    private javax.swing.JLabel dataHora;
    private javax.swing.JButton fichaMedicaButton;
    private javax.swing.JLabel hora;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JList<String> motivos;
    private javax.swing.JLabel nomePaciente;
    // End of variables declaration//GEN-END:variables
}
