/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inter.face;

import medi.flow.Clinica;
import sql.server.*;
import javax.swing.*;

import static medi.flow.Main.clinica;

/**
 *
 * @author Luis
 */
public class ConsultaFuncionario extends javax.swing.JPanel {
    int idConsulta;
    /**
     * Creates new form Consulta
     */
    public ConsultaFuncionario(Clinica.Consulta consulta) {
        initComponents();

        // Preenche os componentes da interface, verificando nulos e usando valores padrão
        nomePaciente.setText(consulta.getNomePaciente() != null ? consulta.getNomePaciente() : "Não disponível");
        nSns.setText(Integer.toString(consulta.getSnsPaciente()));
        medico.setText(consulta.getNomeMedico());
        sala.setText(Integer.toString(consulta.getNumSala()));
        data.setText(consulta.getData() != null ? consulta.getData() : "Não disponível");
        hora.setText(consulta.getHora() != null ? consulta.getHora() : "Não disponível");
        idConsulta = consulta.getIdConsulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        nome = new javax.swing.JLabel();
        sns = new javax.swing.JLabel();
        med = new javax.swing.JLabel();
        sal = new javax.swing.JLabel();
        nomePaciente = new javax.swing.JLabel();
        nSns = new javax.swing.JLabel();
        medico = new javax.swing.JLabel();
        sala = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        botaoDesmarcar = new javax.swing.JButton();
        data = new javax.swing.JLabel();
        h = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 149, 218), 3, true));
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(900, 100));
        setMinimumSize(new java.awt.Dimension(900, 100));
        setPreferredSize(new java.awt.Dimension(900, 100));
        setLayout(new java.awt.GridBagLayout());

        nome.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        nome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nome.setText("Nome do paciente:");
        nome.setMaximumSize(new java.awt.Dimension(150, 30));
        nome.setMinimumSize(new java.awt.Dimension(150, 30));
        nome.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(nome, gridBagConstraints);

        sns.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        sns.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sns.setText("N.º SNS:");
        sns.setMaximumSize(new java.awt.Dimension(150, 30));
        sns.setMinimumSize(new java.awt.Dimension(150, 30));
        sns.setPreferredSize(new java.awt.Dimension(150, 30));
        sns.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(sns, gridBagConstraints);

        med.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        med.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        med.setText("Médico:");
        med.setMaximumSize(new java.awt.Dimension(60, 30));
        med.setMinimumSize(new java.awt.Dimension(60, 30));
        med.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(med, gridBagConstraints);

        sal.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        sal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sal.setText("Sala:");
        sal.setMaximumSize(new java.awt.Dimension(60, 30));
        sal.setMinimumSize(new java.awt.Dimension(60, 30));
        sal.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(sal, gridBagConstraints);

        nomePaciente.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        nomePaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nomePaciente.setText("xxxxxx");
        nomePaciente.setMaximumSize(new java.awt.Dimension(250, 30));
        nomePaciente.setMinimumSize(new java.awt.Dimension(250, 30));
        nomePaciente.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(nomePaciente, gridBagConstraints);

        nSns.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        nSns.setText("yyyyy");
        nSns.setMaximumSize(new java.awt.Dimension(250, 30));
        nSns.setMinimumSize(new java.awt.Dimension(250, 30));
        nSns.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(nSns, gridBagConstraints);

        medico.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        medico.setText("zzzzzzz");
        medico.setMaximumSize(new java.awt.Dimension(150, 30));
        medico.setMinimumSize(new java.awt.Dimension(150, 30));
        medico.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(medico, gridBagConstraints);

        sala.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        sala.setText("wwwww");
        sala.setMaximumSize(new java.awt.Dimension(150, 30));
        sala.setMinimumSize(new java.awt.Dimension(150, 30));
        sala.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(sala, gridBagConstraints);

        d.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        d.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        d.setText("Data:");
        d.setMaximumSize(new java.awt.Dimension(40, 30));
        d.setMinimumSize(new java.awt.Dimension(40, 30));
        d.setPreferredSize(new java.awt.Dimension(40, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        add(d, gridBagConstraints);

        botaoDesmarcar.setBackground(new java.awt.Color(0, 132, 193));
        botaoDesmarcar.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        botaoDesmarcar.setForeground(new java.awt.Color(242, 242, 242));
        botaoDesmarcar.setText("Desmarcar");
        botaoDesmarcar.setPreferredSize(new java.awt.Dimension(100, 35));
        botaoDesmarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDesmarcarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        add(botaoDesmarcar, gridBagConstraints);

        data.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        data.setText("xx/yy/zzzz");
        data.setMaximumSize(new java.awt.Dimension(80, 30));
        data.setMinimumSize(new java.awt.Dimension(80, 30));
        data.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(data, gridBagConstraints);

        h.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        h.setText("Hora:");
        h.setMaximumSize(new java.awt.Dimension(40, 30));
        h.setMinimumSize(new java.awt.Dimension(40, 30));
        h.setPreferredSize(new java.awt.Dimension(40, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        add(h, gridBagConstraints);

        hora.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        hora.setText("hh/mm");
        hora.setMaximumSize(new java.awt.Dimension(80, 30));
        hora.setMinimumSize(new java.awt.Dimension(80, 30));
        hora.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        add(hora, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoDesmarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDesmarcarActionPerformed
        SqlSecretaria.desmarcarConsulta(idConsulta); // Chama o método para desmarcar a consulta na base de dados
        clinica.removeConsulta(idConsulta); // Remove a consulta da lista de consultas da clínica

        JPanel parentPanel = (JPanel) this.getParent(); // Atualiza o painel pai ao remover esta consulta
        parentPanel.remove(this); // remove este painel
        parentPanel.setPreferredSize(new java.awt.Dimension(parentPanel.getWidth(), parentPanel.getHeight() - 100));
        parentPanel.revalidate(); // Atualiza o painel
        parentPanel.repaint(); // Redesenha o painel
    }//GEN-LAST:event_botaoDesmarcarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDesmarcar;
    private javax.swing.JLabel d;
    private javax.swing.JLabel data;
    private javax.swing.JLabel h;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel med;
    private javax.swing.JLabel medico;
    private javax.swing.JLabel nSns;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel nomePaciente;
    private javax.swing.JLabel sal;
    private javax.swing.JLabel sala;
    private javax.swing.JLabel sns;
    // End of variables declaration//GEN-END:variables
}
