/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inter.face;

/**
 *
 * @author draga
 */
public class Credencial extends javax.swing.JPanel {

    /**
     * Creates new form Credencial
     */
    public Credencial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        nomePaciente = new javax.swing.JLabel();
        nSns = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        medico = new javax.swing.JLabel();
        sala = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        botaoDesmarcar1 = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 149, 218), 3, true));
        setLayout(new java.awt.GridBagLayout());

        nomePaciente.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        nomePaciente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nomePaciente.setText("ID:");
        nomePaciente.setMaximumSize(new java.awt.Dimension(120, 30));
        nomePaciente.setMinimumSize(new java.awt.Dimension(120, 30));
        nomePaciente.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(nomePaciente, gridBagConstraints);

        nSns.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        nSns.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nSns.setText("Nome");
        nSns.setMaximumSize(new java.awt.Dimension(120, 30));
        nSns.setMinimumSize(new java.awt.Dimension(120, 30));
        nSns.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(nSns, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("xxxxxx");
        jLabel6.setMaximumSize(new java.awt.Dimension(350, 30));
        jLabel6.setMinimumSize(new java.awt.Dimension(350, 30));
        jLabel6.setPreferredSize(new java.awt.Dimension(350, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel7.setText("yyyyy");
        jLabel7.setMaximumSize(new java.awt.Dimension(350, 30));
        jLabel7.setMinimumSize(new java.awt.Dimension(350, 30));
        jLabel7.setPreferredSize(new java.awt.Dimension(350, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(jLabel7, gridBagConstraints);

        medico.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        medico.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medico.setText("Password:");
        medico.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        medico.setMaximumSize(new java.awt.Dimension(80, 30));
        medico.setMinimumSize(new java.awt.Dimension(80, 30));
        medico.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(medico, gridBagConstraints);

        sala.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        sala.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sala.setText("Função:");
        sala.setMaximumSize(new java.awt.Dimension(80, 30));
        sala.setMinimumSize(new java.awt.Dimension(80, 30));
        sala.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(sala, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel8.setText("zzzzzzz");
        jLabel8.setMaximumSize(new java.awt.Dimension(175, 30));
        jLabel8.setMinimumSize(new java.awt.Dimension(175, 30));
        jLabel8.setPreferredSize(new java.awt.Dimension(175, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel9.setText("wwwww");
        jLabel9.setMaximumSize(new java.awt.Dimension(175, 30));
        jLabel9.setMinimumSize(new java.awt.Dimension(175, 30));
        jLabel9.setPreferredSize(new java.awt.Dimension(175, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(jLabel9, gridBagConstraints);

        botaoDesmarcar1.setBackground(new java.awt.Color(0, 132, 193));
        botaoDesmarcar1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        botaoDesmarcar1.setForeground(new java.awt.Color(245, 245, 245));
        botaoDesmarcar1.setText("Eliminar");
        botaoDesmarcar1.setPreferredSize(new java.awt.Dimension(100, 35));
        botaoDesmarcar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDesmarcar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        add(botaoDesmarcar1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoDesmarcar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDesmarcar1ActionPerformed

    }//GEN-LAST:event_botaoDesmarcar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDesmarcar;
    private javax.swing.JButton botaoDesmarcar1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel medico;
    private javax.swing.JLabel nSns;
    private javax.swing.JLabel nomePaciente;
    private javax.swing.JLabel sala;
    // End of variables declaration//GEN-END:variables
}
