/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inter.face;

import java.util.*;

/**
 *
 * @author Luis
 */
public class Credencial extends javax.swing.JPanel {

    /**
     * Creates new form Credencial
     */

    private VistaGestor vistaGestor;
    private String id;

    public Credencial(HashMap<String, String> dados, VistaGestor vistaGestor) {
        this.vistaGestor = vistaGestor;
        this.id = dados.get("ID");
        initComponents();

        idCredencial.setText(dados.getOrDefault("ID", "ID não disponível"));
        nomeCredencial.setText(dados.getOrDefault("Nome", "Nome não disponível"));
        password.setText(dados.getOrDefault("Password", "Password não disponível"));
        funcao.setText(dados.getOrDefault("TipoUtilizador", "Função não disponível"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        nomePaciente = new javax.swing.JLabel();
        nSns = new javax.swing.JLabel();
        idCredencial = new javax.swing.JLabel();
        nomeCredencial = new javax.swing.JLabel();
        medico = new javax.swing.JLabel();
        sala = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        funcao = new javax.swing.JLabel();
        botaoDesmarcar1 = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 149, 218), 3, true));
        setLayout(new java.awt.GridBagLayout());

        nomePaciente.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        nomePaciente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nomePaciente.setText("ID:");
        nomePaciente.setMaximumSize(new java.awt.Dimension(120, 30));
        nomePaciente.setMinimumSize(new java.awt.Dimension(120, 30));
        nomePaciente.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(nomePaciente, gridBagConstraints);

        nSns.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        nSns.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nSns.setText("Nome");
        nSns.setMaximumSize(new java.awt.Dimension(120, 30));
        nSns.setMinimumSize(new java.awt.Dimension(120, 30));
        nSns.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(nSns, gridBagConstraints);

        idCredencial.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        idCredencial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        idCredencial.setText("xxxxxx");
        idCredencial.setMaximumSize(new java.awt.Dimension(350, 30));
        idCredencial.setMinimumSize(new java.awt.Dimension(350, 30));
        idCredencial.setPreferredSize(new java.awt.Dimension(350, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(idCredencial, gridBagConstraints);

        nomeCredencial.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        nomeCredencial.setText("yyyyy");
        nomeCredencial.setMaximumSize(new java.awt.Dimension(350, 30));
        nomeCredencial.setMinimumSize(new java.awt.Dimension(350, 30));
        nomeCredencial.setPreferredSize(new java.awt.Dimension(350, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(nomeCredencial, gridBagConstraints);

        medico.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        medico.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medico.setText("Password:");
        medico.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        medico.setMaximumSize(new java.awt.Dimension(80, 30));
        medico.setMinimumSize(new java.awt.Dimension(80, 30));
        medico.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(medico, gridBagConstraints);

        sala.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        sala.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sala.setText("Função:");
        sala.setMaximumSize(new java.awt.Dimension(80, 30));
        sala.setMinimumSize(new java.awt.Dimension(80, 30));
        sala.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(sala, gridBagConstraints);

        password.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        password.setText("zzzzzzz");
        password.setMaximumSize(new java.awt.Dimension(175, 30));
        password.setMinimumSize(new java.awt.Dimension(175, 30));
        password.setPreferredSize(new java.awt.Dimension(175, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(password, gridBagConstraints);

        funcao.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        funcao.setText("wwwww");
        funcao.setMaximumSize(new java.awt.Dimension(175, 30));
        funcao.setMinimumSize(new java.awt.Dimension(175, 30));
        funcao.setPreferredSize(new java.awt.Dimension(175, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(funcao, gridBagConstraints);

        botaoDesmarcar1.setBackground(new java.awt.Color(0, 132, 193));
        botaoDesmarcar1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        botaoDesmarcar1.setForeground(new java.awt.Color(245, 245, 245));
        botaoDesmarcar1.setText("Eliminar");
        botaoDesmarcar1.setPreferredSize(new java.awt.Dimension(100, 35));
        botaoDesmarcar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDesmarcar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        add(botaoDesmarcar1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoDesmarcar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDesmarcar1ActionPerformed
        vistaGestor.mostrarPainelSenha(id);
    }//GEN-LAST:event_botaoDesmarcar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDesmarcar1;
    private javax.swing.JLabel funcao;
    private javax.swing.JLabel idCredencial;
    private javax.swing.JLabel medico;
    private javax.swing.JLabel nSns;
    private javax.swing.JLabel nomeCredencial;
    private javax.swing.JLabel nomePaciente;
    private javax.swing.JLabel password;
    private javax.swing.JLabel sala;
    // End of variables declaration//GEN-END:variables
}
