/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inter.face;

import java.util.List;

/**
 *
 * @author Luís
 */
// Classe que representa a interface de um registo clínico
public class EntradaRegistoClinicoPanel extends javax.swing.JPanel {

    /**
     * Creates new form EntradaRegistoClinicoPanel
     */
    // Construtor da classe
    public EntradaRegistoClinicoPanel(List<String> assunto, List<String> tratamento) {
        initComponents();// Inicializa os componentes da interface
        motivoList.setListData(assunto.toArray(new String[0]));// Preenche a lista de motivos da consulta
        tratamentoList.setListData(tratamento.toArray(new String[0]));// Preenche a lista de tratamentos da consulta
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        motivoList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tratamentoList = new javax.swing.JList<>();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 149, 218), 3, true));
        setMaximumSize(new java.awt.Dimension(538, 220));
        setMinimumSize(new java.awt.Dimension(538, 220));
        setPreferredSize(new java.awt.Dimension(538, 220));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Motivo:");
        jLabel1.setMaximumSize(new java.awt.Dimension(80, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(80, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 80, 5);
        add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tratamentos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 80, 5);
        add(jLabel2, gridBagConstraints);

        jScrollPane1.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 100));

        motivoList.setBackground(new java.awt.Color(242, 242, 242));
        motivoList.setBorder(null);
        motivoList.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        motivoList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(motivoList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(jScrollPane1, gridBagConstraints);

        jScrollPane2.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPane2.setBorder(null);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 100));

        tratamentoList.setBackground(new java.awt.Color(242, 242, 242));
        tratamentoList.setBorder(null);
        tratamentoList.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        tratamentoList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(tratamentoList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(jScrollPane2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> motivoList;
    private javax.swing.JList<String> tratamentoList;
    // End of variables declaration//GEN-END:variables
}
