/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inter.face;

import medi.flow.Clinica;

/**
 *
 * @author draga
 */
public class HorariosMedico extends javax.swing.JFrame {

    /**
     * Creates new form HorariosMedico
     */
    public HorariosMedico() {
        initComponents();
    }

    public void carregarHorarios() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dia2 = new javax.swing.JLabel();
        dia3 = new javax.swing.JLabel();
        dia5 = new javax.swing.JLabel();
        horariosDia2 = new javax.swing.JList<>();
        horariosDia3 = new javax.swing.JList<>();
        horariosDia5 = new javax.swing.JList<>();
        dia4 = new javax.swing.JLabel();
        horariosDia4 = new javax.swing.JList<>();
        dia1 = new javax.swing.JLabel();
        horariosDia1 = new javax.swing.JList<>();
        horariosDias = new javax.swing.JLabel();
        nomeMedico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 300));
        setPreferredSize(new java.awt.Dimension(450, 350));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        dia2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        dia2.setText(" 27/12");
        dia2.setMaximumSize(new java.awt.Dimension(70, 20));
        dia2.setMinimumSize(new java.awt.Dimension(70, 20));
        dia2.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        getContentPane().add(dia2, gridBagConstraints);

        dia3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        dia3.setText(" 28/12");
        dia3.setMaximumSize(new java.awt.Dimension(70, 20));
        dia3.setMinimumSize(new java.awt.Dimension(70, 20));
        dia3.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        getContentPane().add(dia3, gridBagConstraints);

        dia5.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        dia5.setText(" 31/12");
        dia5.setMaximumSize(new java.awt.Dimension(70, 20));
        dia5.setMinimumSize(new java.awt.Dimension(70, 20));
        dia5.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        getContentPane().add(dia5, gridBagConstraints);

        horariosDia2.setBackground(new java.awt.Color(242, 242, 242));
        horariosDia2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 149, 218), 2, true));
        horariosDia2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        horariosDia2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "9h-10h", "10h-11h", "11h-12h", "12h-13h", "14h-15h", "15h-16h", "16h-17h", "17h-18h" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        horariosDia2.setMaximumSize(new java.awt.Dimension(70, 200));
        horariosDia2.setMinimumSize(new java.awt.Dimension(70, 200));
        horariosDia2.setPreferredSize(new java.awt.Dimension(70, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        getContentPane().add(horariosDia2, gridBagConstraints);

        horariosDia3.setBackground(new java.awt.Color(242, 242, 242));
        horariosDia3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 149, 218), 2, true));
        horariosDia3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        horariosDia3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "9h-10h", "10h-11h", "11h-12h", "12h-13h", "14h-15h", "15h-16h", "16h-17h", "17h-18h" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        horariosDia3.setMaximumSize(new java.awt.Dimension(70, 200));
        horariosDia3.setMinimumSize(new java.awt.Dimension(70, 200));
        horariosDia3.setPreferredSize(new java.awt.Dimension(70, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        getContentPane().add(horariosDia3, gridBagConstraints);

        horariosDia5.setBackground(new java.awt.Color(242, 242, 242));
        horariosDia5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 149, 218), 2, true));
        horariosDia5.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        horariosDia5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "9h-10h", "10h-11h", "11h-12h", "12h-13h", "14h-15h", "15h-16h", "16h-17h", "17h-18h" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        horariosDia5.setMaximumSize(new java.awt.Dimension(70, 200));
        horariosDia5.setMinimumSize(new java.awt.Dimension(70, 200));
        horariosDia5.setPreferredSize(new java.awt.Dimension(70, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        getContentPane().add(horariosDia5, gridBagConstraints);

        dia4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        dia4.setText(" 30/12");
        dia4.setMaximumSize(new java.awt.Dimension(70, 20));
        dia4.setMinimumSize(new java.awt.Dimension(70, 20));
        dia4.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        getContentPane().add(dia4, gridBagConstraints);

        horariosDia4.setBackground(new java.awt.Color(242, 242, 242));
        horariosDia4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 149, 218), 2, true));
        horariosDia4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        horariosDia4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "9h-10h", "10h-11h", "11h-12h", "12h-13h", "14h-15h", "15h-16h", "16h-17h", "17h-18h" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        horariosDia4.setMaximumSize(new java.awt.Dimension(70, 200));
        horariosDia4.setMinimumSize(new java.awt.Dimension(70, 200));
        horariosDia4.setPreferredSize(new java.awt.Dimension(70, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        getContentPane().add(horariosDia4, gridBagConstraints);

        dia1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        dia1.setText(" 26/12");
        dia1.setMaximumSize(new java.awt.Dimension(70, 20));
        dia1.setMinimumSize(new java.awt.Dimension(70, 20));
        dia1.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(dia1, gridBagConstraints);

        horariosDia1.setBackground(new java.awt.Color(242, 242, 242));
        horariosDia1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 149, 218), 2, true));
        horariosDia1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        horariosDia1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "9h-10h", "10h-11h", "11h-12h", "12h-13h", "14h-15h", "15h-16h", "16h-17h", "17h-18h" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        horariosDia1.setMaximumSize(new java.awt.Dimension(70, 200));
        horariosDia1.setMinimumSize(new java.awt.Dimension(70, 200));
        horariosDia1.setPreferredSize(new java.awt.Dimension(70, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(horariosDia1, gridBagConstraints);

        horariosDias.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        horariosDias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horariosDias.setText("Horarios dos dias: dd/mm - dd/mm");
        horariosDias.setMaximumSize(new java.awt.Dimension(250, 30));
        horariosDias.setMinimumSize(new java.awt.Dimension(250, 30));
        horariosDias.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        getContentPane().add(horariosDias, gridBagConstraints);

        nomeMedico.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        nomeMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeMedico.setText("Dr. xxxxxxxxxyyyyyyyyyyyyyyyyy");
        nomeMedico.setMaximumSize(new java.awt.Dimension(250, 30));
        nomeMedico.setMinimumSize(new java.awt.Dimension(250, 30));
        nomeMedico.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        getContentPane().add(nomeMedico, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */



    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HorariosMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HorariosMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HorariosMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HorariosMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HorariosMedico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dia1;
    private javax.swing.JLabel dia2;
    private javax.swing.JLabel dia3;
    private javax.swing.JLabel dia4;
    private javax.swing.JLabel dia5;
    private javax.swing.JList<String> horariosDia1;
    private javax.swing.JList<String> horariosDia2;
    private javax.swing.JList<String> horariosDia3;
    private javax.swing.JList<String> horariosDia4;
    private javax.swing.JList<String> horariosDia5;
    private javax.swing.JLabel horariosDias;
    private javax.swing.JLabel nomeMedico;
    // End of variables declaration//GEN-END:variables
}
