/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inter.face;

import medi.flow.Consulta;
import medi.flow.RegistoClinico;

import java.util.List;

import static medi.flow.Main.getClinica;
import static medi.flow.Text.splitStringToList;
import static sql.server.SqlMedico.criarNovaEntrada;

/**
 *
 * @author Luis
 */
// Classe que cria a interface gráfica para a criação de uma nova entrada de registo clínico
public class NovaEntradaRC extends javax.swing.JFrame {
    static Consulta consulta;
    /**
     * Creates new form NovaEntradaRC
     */
    // Construtor da classe
    public NovaEntradaRC(Consulta consulta) {
        initComponents();
        this.consulta = consulta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        assuntosArea = new javax.swing.JTextArea();
        tratamentosArea = new javax.swing.JTextArea();
        concluirButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 720));
        setMinimumSize(new java.awt.Dimension(720, 720));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(720, 660));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Assunto:");
        jLabel2.setMaximumSize(new java.awt.Dimension(81, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(81, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(81, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 230, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Tratamentos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 230, 0);
        jPanel2.add(jLabel3, gridBagConstraints);

        assuntosArea.setColumns(20);
        assuntosArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        assuntosArea.setLineWrap(true);
        assuntosArea.setRows(5);
        assuntosArea.setWrapStyleWord(true);
        assuntosArea.setMinimumSize(new java.awt.Dimension(500, 250));
        assuntosArea.setPreferredSize(new java.awt.Dimension(500, 250));
        jPanel2.add(assuntosArea, new java.awt.GridBagConstraints());

        tratamentosArea.setColumns(20);
        tratamentosArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        tratamentosArea.setLineWrap(true);
        tratamentosArea.setRows(5);
        tratamentosArea.setWrapStyleWord(true);
        tratamentosArea.setMinimumSize(new java.awt.Dimension(500, 250));
        tratamentosArea.setPreferredSize(new java.awt.Dimension(500, 250));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel2.add(tratamentosArea, gridBagConstraints);

        concluirButton.setBackground(new java.awt.Color(0, 132, 193));
        concluirButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        concluirButton.setForeground(new java.awt.Color(242, 242, 242));
        concluirButton.setText("CONCLUIR");
        concluirButton.setMaximumSize(new java.awt.Dimension(140, 35));
        concluirButton.setMinimumSize(new java.awt.Dimension(140, 35));
        concluirButton.setPreferredSize(new java.awt.Dimension(140, 35));
        concluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluirButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(25, 350, 0, 0);
        jPanel2.add(concluirButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(0, 149, 218));
        jPanel3.setPreferredSize(new java.awt.Dimension(720, 60));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("MediFlow");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 60));
        jLabel1.setMinimumSize(new java.awt.Dimension(140, 60));
        jLabel1.setPreferredSize(new java.awt.Dimension(140, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 430);
        jPanel3.add(jLabel1, gridBagConstraints);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel5.setToolTipText("");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 640);
        jPanel3.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Método que é chamado quando o botão de guardar é pressionado
    private void concluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirButtonActionPerformed
        String assuntos = assuntosArea.getText();
        String tratamentos = tratamentosArea.getText();

        if (assuntos.isEmpty() || tratamentos.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos.");
        }else{
            List<String> assunto = splitStringToList(assuntos);
            List<String> tratamento = splitStringToList(tratamentos);


            RegistoClinico.EntradaRegistoClinico entrada = null;
            for (RegistoClinico registo : getClinica().getRegistos()) {
                if (registo.getNumeroSns() == consulta.getSnsPaciente()) {
                    entrada = registo.new EntradaRegistoClinico(consulta.getIdMedico(), consulta.getData(), assunto, tratamento);
                    registo.addEntradaRegistoClinico(entrada);
                    break;
                }
            }

            criarNovaEntrada(entrada);

            javax.swing.JOptionPane.showMessageDialog(this, "Entrada criada com sucesso.");
            dispose();
        }
    }//GEN-LAST:event_concluirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Método main que cria a interface gráfica
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaEntradaRC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaEntradaRC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaEntradaRC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaEntradaRC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaEntradaRC(consulta).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea assuntosArea;
    private javax.swing.JButton concluirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextArea tratamentosArea;
    // End of variables declaration//GEN-END:variables
}
