/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inter.face;

import javax.swing.*;

/**
 *
 * @author draga
 */
public class ReceitarMedicacao extends javax.swing.JFrame {

    /**
     * Creates new form ReceitarMedicacao
     */
    public ReceitarMedicacao() {
        initComponents();

        // Configurar o modelo da lista
        DefaultListModel<String> medicamentoModel = new DefaultListModel<>();
        jList1.setModel(medicamentoModel);

        // Configurar o menu de contexto para a lista
        configurarPopupMenu(jList1, medicamentoModel);
    }

    private void configurarPopupMenu(JList<String> list, DefaultListModel<String> model) {
        // Criar o menu de contexto
        JPopupMenu popupMenu = new JPopupMenu();

        // Opção "Editar"
        JMenuItem editarItem = new JMenuItem("Editar");
        editarItem.addActionListener(e -> {
            int selectedIndex = list.getSelectedIndex();
            if (selectedIndex != -1) {
                String valorAtual = model.get(selectedIndex);
                String novoValor = JOptionPane.showInputDialog(
                    this,
                    "Editar medicamento e quantidade (ex.: Paracetamol - 500mg):",
                    valorAtual
                );
                if (novoValor != null && !novoValor.trim().isEmpty()) {
                    model.set(selectedIndex, novoValor);
                }
            }
        });

        // Opção "Adicionar"
        JMenuItem adicionarItem = new JMenuItem("Adicionar");
        adicionarItem.addActionListener(e -> {
            String novoMedicamento = JOptionPane.showInputDialog(
                this,
                "Adicionar medicamento e quantidade (ex.: 1xParacetamol - 500mg):"
            );
            if (novoMedicamento != null && !novoMedicamento.trim().isEmpty()) {
                model.addElement(novoMedicamento);
            }
        });

        // Adicionar opções ao menu
        popupMenu.add(editarItem);
        popupMenu.add(adicionarItem);

        // Associar o menu de contexto à lista
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                if (evt.isPopupTrigger()) {
                    list.setSelectedIndex(list.locationToIndex(evt.getPoint()));
                    popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }

            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                if (evt.isPopupTrigger()) {
                    list.setSelectedIndex(list.locationToIndex(evt.getPoint()));
                    popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }
        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        snsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 350));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(350, 200));

        jList1.setBackground(new java.awt.Color(242, 242, 242));
        jList1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 149, 218), 3, true));
        jList1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setPreferredSize(new java.awt.Dimension(350, 200));
        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        snsButton.setBackground(new java.awt.Color(0, 132, 193));
        snsButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        snsButton.setForeground(new java.awt.Color(242, 242, 242));
        snsButton.setText("CONCLUIR");
        snsButton.setMaximumSize(new java.awt.Dimension(120, 30));
        snsButton.setMinimumSize(new java.awt.Dimension(120, 30));
        snsButton.setPreferredSize(new java.awt.Dimension(120, 30));
        snsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snsButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        getContentPane().add(snsButton, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setText("Receitar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void snsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snsButtonActionPerformed
        DefaultListModel<String> model = (DefaultListModel<String>) jList1.getModel();
        boolean formatoCorreto = true;

        // Verificar o formato de cada item
        for (int i = 0; i < model.size(); i++) {
            String item = model.get(i);
            if (!item.matches("^\\d+x[A-Za-zÀ-ÿ\\s]+ - \\d+mg$")) {
                formatoCorreto = false;
                JOptionPane.showMessageDialog(
                    this,
                    "O item \"" + item + "\" está em um formato inválido.\nUse o formato: 1xParacetamol - 500mg",
                    "Erro de Formato",
                    JOptionPane.ERROR_MESSAGE
                );
                break;
            }
        }

        if (formatoCorreto) {
            // Mostrar opções de "Enviar para SNS" ou "Imprimir"
            int escolha = JOptionPane.showOptionDialog(
                this,
                "Escolha a ação:",
                "Concluir Receita",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"Enviar para SNS", "Imprimir"},
                "Enviar para SNS"
            );

            if (escolha == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Receita enviada para o SNS!");
            } else if (escolha == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(this, "Receita imprimida!");
            }

            // Fechar a janela
            dispose();
        }
    }//GEN-LAST:event_snsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceitarMedicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceitarMedicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceitarMedicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceitarMedicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceitarMedicacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton snsButton;
    // End of variables declaration//GEN-END:variables
}
