/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inter.face;

import medi.flow.Clinica;
import medi.flow.Paciente;

import java.util.List;

import static medi.flow.Main.getClinica;

/**
 *
 * @author Luis
 */
public class RegistoClinico extends javax.swing.JFrame {

    /**
     * Creates new form FichaMedica
     */
    public RegistoClinico(Clinica.RegistroClinico registroClinico) {
        initComponents();

        String nome = "";
        int contactoPaciente = 0;
        int sns = registroClinico.getNumeroSns();
        List<Paciente> listaPacientes = getClinica().getPacientes();
        for (Paciente paciente : listaPacientes) {
            if (paciente.getNumeroSNS() == sns){
                nome = paciente.getNome();
                contactoPaciente = paciente.getContacto();
            }
        }
        int numeroSns = registroClinico.getNumeroSns();
        List<String> alergias = registroClinico.getAlergias();
        List<String> operacoes = registroClinico.getOperacoes();
        List<String> historicoDoencas = registroClinico.getHistoricoDoencas();

        nomePaciente.setText(nome);
        nSns.setText(String.valueOf(sns));
        contacto.setText(String.valueOf(contactoPaciente));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        entradasPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adicionarEntrada = new javax.swing.JButton();
        nomePaciente = new javax.swing.JLabel();
        nSns = new javax.swing.JLabel();
        contacto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        receitarMed = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alergiasPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tratamentosPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        doencasPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(1080, 660));
        jPanel3.setPreferredSize(new java.awt.Dimension(1080, 660));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(538, 10000));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(538, 10000));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(538, 10000));

        entradasPanel.setMaximumSize(new java.awt.Dimension(538, 0));
        entradasPanel.setMinimumSize(new java.awt.Dimension(538, 0));
        entradasPanel.setPreferredSize(new java.awt.Dimension(538, 0));

        javax.swing.GroupLayout entradasPanelLayout = new javax.swing.GroupLayout(entradasPanel);
        entradasPanel.setLayout(entradasPanelLayout);
        entradasPanelLayout.setHorizontalGroup(
            entradasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        entradasPanelLayout.setVerticalGroup(
            entradasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5328, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(entradasPanel);

        jPanel3.add(jScrollPane2, new java.awt.GridBagConstraints());

        jPanel7.setBackground(new java.awt.Color(0, 149, 218));
        jPanel7.setMaximumSize(new java.awt.Dimension(4, 660));
        jPanel7.setMinimumSize(new java.awt.Dimension(4, 660));
        jPanel7.setPreferredSize(new java.awt.Dimension(4, 660));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jPanel7, gridBagConstraints);

        jPanel8.setMaximumSize(new java.awt.Dimension(538, 660));
        jPanel8.setMinimumSize(new java.awt.Dimension(538, 660));
        jPanel8.setPreferredSize(new java.awt.Dimension(538, 660));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jPanel9.setMaximumSize(new java.awt.Dimension(538, 216));
        jPanel9.setMinimumSize(new java.awt.Dimension(538, 216));
        jPanel9.setPreferredSize(new java.awt.Dimension(538, 216));
        jPanel9.setRequestFocusEnabled(false);
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setText("INFORMAÇÕES PESSOAIS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 300);
        jPanel9.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setText("Nome:");
        jLabel3.setMaximumSize(new java.awt.Dimension(75, 20));
        jLabel3.setMinimumSize(new java.awt.Dimension(75, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(75, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 400);
        jPanel9.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setText("Número do SNS:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 375);
        jPanel9.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setText("Contacto:");
        jLabel5.setMaximumSize(new java.awt.Dimension(75, 20));
        jLabel5.setMinimumSize(new java.awt.Dimension(75, 20));
        jLabel5.setPreferredSize(new java.awt.Dimension(75, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 400);
        jPanel9.add(jLabel5, gridBagConstraints);

        adicionarEntrada.setBackground(new java.awt.Color(0, 132, 193));
        adicionarEntrada.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        adicionarEntrada.setForeground(new java.awt.Color(242, 242, 242));
        adicionarEntrada.setText("Adicionar Entrada");
        adicionarEntrada.setMaximumSize(new java.awt.Dimension(150, 30));
        adicionarEntrada.setMinimumSize(new java.awt.Dimension(150, 30));
        adicionarEntrada.setPreferredSize(new java.awt.Dimension(150, 30));
        adicionarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarEntradaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 250, 0, 0);
        jPanel9.add(adicionarEntrada, gridBagConstraints);

        nomePaciente.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        nomePaciente.setText("Luis Claudio Da Silva Junior");
        nomePaciente.setToolTipText("");
        nomePaciente.setMaximumSize(new java.awt.Dimension(390, 20));
        nomePaciente.setMinimumSize(new java.awt.Dimension(390, 20));
        nomePaciente.setPreferredSize(new java.awt.Dimension(390, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel9.add(nomePaciente, gridBagConstraints);

        nSns.setText("12457845121");
        nSns.setMaximumSize(new java.awt.Dimension(100, 20));
        nSns.setMinimumSize(new java.awt.Dimension(100, 20));
        nSns.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 160);
        jPanel9.add(nSns, gridBagConstraints);

        contacto.setText("123456789");
        contacto.setMaximumSize(new java.awt.Dimension(100, 20));
        contacto.setMinimumSize(new java.awt.Dimension(100, 20));
        contacto.setPreferredSize(new java.awt.Dimension(100, 20));
        contacto.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 250);
        jPanel9.add(contacto, gridBagConstraints);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel9.add(jPanel2, gridBagConstraints);

        receitarMed.setBackground(new java.awt.Color(0, 132, 193));
        receitarMed.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        receitarMed.setForeground(new java.awt.Color(242, 242, 242));
        receitarMed.setText("Receitar");
        receitarMed.setMaximumSize(new java.awt.Dimension(150, 30));
        receitarMed.setMinimumSize(new java.awt.Dimension(150, 30));
        receitarMed.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 250, 0, 0);
        jPanel9.add(receitarMed, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel8.add(jPanel9, gridBagConstraints);

        jPanel10.setBackground(new java.awt.Color(0, 149, 218));
        jPanel10.setForeground(new java.awt.Color(0, 149, 218));
        jPanel10.setMaximumSize(new java.awt.Dimension(538, 4));
        jPanel10.setMinimumSize(new java.awt.Dimension(538, 4));
        jPanel10.setPreferredSize(new java.awt.Dimension(538, 4));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel8.add(jPanel10, gridBagConstraints);

        jPanel11.setMaximumSize(new java.awt.Dimension(538, 440));
        jPanel11.setMinimumSize(new java.awt.Dimension(538, 440));
        jPanel11.setPreferredSize(new java.awt.Dimension(538, 440));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setText("INFORMAÇÕES MÉDICAS");
        jLabel6.setMaximumSize(new java.awt.Dimension(212, 25));
        jLabel6.setMinimumSize(new java.awt.Dimension(212, 25));
        jLabel6.setPreferredSize(new java.awt.Dimension(212, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 300);
        jPanel11.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Alergias:");
        jLabel7.setMaximumSize(new java.awt.Dimension(140, 20));
        jLabel7.setMinimumSize(new java.awt.Dimension(140, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 100, 350);
        jPanel11.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Tratamentos:");
        jLabel8.setMaximumSize(new java.awt.Dimension(140, 20));
        jLabel8.setMinimumSize(new java.awt.Dimension(140, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 100, 350);
        jPanel11.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Histórico de doenças:");
        jLabel9.setMaximumSize(new java.awt.Dimension(140, 20));
        jLabel9.setMinimumSize(new java.awt.Dimension(140, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 100, 350);
        jPanel11.add(jLabel9, gridBagConstraints);

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 120));

        alergiasPanel.setPreferredSize(new java.awt.Dimension(298, 0));
        alergiasPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 2));
        jScrollPane1.setViewportView(alergiasPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 0);
        jPanel11.add(jScrollPane1, gridBagConstraints);

        jScrollPane3.setBorder(null);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(300, 120));

        tratamentosPanel.setPreferredSize(new java.awt.Dimension(298, 0));
        tratamentosPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 2));
        jScrollPane3.setViewportView(tratamentosPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 0);
        jPanel11.add(jScrollPane3, gridBagConstraints);

        jScrollPane4.setBorder(null);
        jScrollPane4.setPreferredSize(new java.awt.Dimension(300, 120));

        doencasPanel.setPreferredSize(new java.awt.Dimension(298, 0));
        doencasPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 2));
        jScrollPane4.setViewportView(doencasPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 0);
        jPanel11.add(jScrollPane4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel8.add(jPanel11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jPanel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(0, 149, 218));
        jPanel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 60));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("MediFlow");
        jLabel1.setMaximumSize(new java.awt.Dimension(250, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(140, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 825);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1000);
        jPanel1.add(jLabel12, gridBagConstraints);

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarEntradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistoClinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistoClinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistoClinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistoClinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new RegistoClinico().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarEntrada;
    private javax.swing.JPanel alergiasPanel;
    private javax.swing.JLabel contacto;
    private javax.swing.JPanel doencasPanel;
    private javax.swing.JPanel entradasPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel nSns;
    private javax.swing.JLabel nomePaciente;
    private javax.swing.JButton receitarMed;
    private javax.swing.JPanel tratamentosPanel;
    // End of variables declaration//GEN-END:variables
}
