/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inter.face;


import medi.flow.*;

import javax.swing.*;
import java.util.List;

import static medi.flow.Main.getClinica;


/**
 *
 * @author Luis
 */
public class RegistoClinicoPanel extends javax.swing.JFrame {
    Consulta consulta;
    /**
     * Creates new form FichaMedica
     */
    public RegistoClinicoPanel(RegistoClinico rc, Consulta consulta) {
        initComponents();

        String[] infoPaciente = rc.getInfoPaciente();
        this.consulta = consulta;

        //Obter as informações do paciente a partir do número de sns
        nomePaciente.setText(infoPaciente[0]);
        nSns.setText(String.valueOf(rc.getNumeroSns()));
        contacto.setText(infoPaciente[1]);

        //Obter os dados das Listas
        List<String> alergias = rc.getAlergias();
        List<String> tratamentos = rc.getOperacoes();
        List<String> doencas = rc.getHistoricoDoencas();

        //Preencher as listas de alergias, tratamentos e doenças
        alergiasList.setListData(alergias.toArray(new String[0]));
        operacoesList.setListData(tratamentos.toArray(new String[0]));
        histDoencasList.setListData(doencas.toArray(new String[0]));
        
        //Carregar as entradas do registo clinico
        carregarEntradas(rc.getEntradasRegistoClinico());
    }

    public void carregarEntradas(List<RegistoClinico.EntradaRegistoClinico> entradas) {
        int tamanhoPainelEntradas = 0;
        entradasPanel.removeAll();
        for (RegistoClinico.EntradaRegistoClinico entrada : entradas) {
            tamanhoPainelEntradas += 220;
            entradasPanel.setPreferredSize(new java.awt.Dimension(538, tamanhoPainelEntradas));
            criarPainelEntrada(entrada.getAssunto(), entrada.getTratamentos());
        }

        // Move a barra de scroll para o topo do painel de consultas
        SwingUtilities.invokeLater(() -> {
            JScrollBar verticalScrollBar = entradasScroll.getVerticalScrollBar();
            verticalScrollBar.setValue(verticalScrollBar.getMinimum());
        });

        entradasPanel.revalidate();
        entradasPanel.repaint();
    }

    void criarPainelEntrada(List<String> assunto, List<String> tratamento){
        //cria um painel para cada entrada
        EntradaRegistoClinicoPanel entradaPanel = new EntradaRegistoClinicoPanel(assunto, tratamento);
        entradasPanel.add(entradaPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        entradasScroll = new javax.swing.JScrollPane();
        entradasPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adicionarEntrada = new javax.swing.JButton();
        nomePaciente = new javax.swing.JLabel();
        nSns = new javax.swing.JLabel();
        contacto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        receitarMed = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        alergiasList = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        operacoesList = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        histDoencasList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(1080, 660));
        jPanel3.setPreferredSize(new java.awt.Dimension(1080, 660));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        entradasScroll.setBorder(null);
        entradasScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        entradasScroll.setMaximumSize(new java.awt.Dimension(538, 32767));
        entradasScroll.setMinimumSize(new java.awt.Dimension(538, 660));
        entradasScroll.setPreferredSize(new java.awt.Dimension(538, 660));

        entradasPanel.setMaximumSize(new java.awt.Dimension(538, 100000));
        entradasPanel.setMinimumSize(new java.awt.Dimension(538, 0));
        entradasPanel.setPreferredSize(new java.awt.Dimension(538, 0));
        entradasPanel.setLayout(new java.awt.GridLayout(0, 1, 10, 10));
        entradasScroll.setViewportView(entradasPanel);

        jPanel3.add(entradasScroll, new java.awt.GridBagConstraints());

        jPanel7.setBackground(new java.awt.Color(0, 149, 218));
        jPanel7.setMaximumSize(new java.awt.Dimension(4, 660));
        jPanel7.setMinimumSize(new java.awt.Dimension(4, 660));
        jPanel7.setPreferredSize(new java.awt.Dimension(4, 660));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jPanel7, gridBagConstraints);

        jPanel8.setMaximumSize(new java.awt.Dimension(538, 660));
        jPanel8.setMinimumSize(new java.awt.Dimension(538, 660));
        jPanel8.setPreferredSize(new java.awt.Dimension(538, 660));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jPanel9.setMaximumSize(new java.awt.Dimension(538, 216));
        jPanel9.setMinimumSize(new java.awt.Dimension(538, 216));
        jPanel9.setPreferredSize(new java.awt.Dimension(538, 216));
        jPanel9.setRequestFocusEnabled(false);
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setText("INFORMAÇÕES PESSOAIS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 300);
        jPanel9.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setText("Nome:");
        jLabel3.setMaximumSize(new java.awt.Dimension(75, 20));
        jLabel3.setMinimumSize(new java.awt.Dimension(75, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(75, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 400);
        jPanel9.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setText("Número do SNS:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 375);
        jPanel9.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setText("Contacto:");
        jLabel5.setMaximumSize(new java.awt.Dimension(75, 20));
        jLabel5.setMinimumSize(new java.awt.Dimension(75, 20));
        jLabel5.setPreferredSize(new java.awt.Dimension(75, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 400);
        jPanel9.add(jLabel5, gridBagConstraints);

        adicionarEntrada.setBackground(new java.awt.Color(0, 132, 193));
        adicionarEntrada.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        adicionarEntrada.setForeground(new java.awt.Color(242, 242, 242));
        adicionarEntrada.setText("Adicionar Entrada");
        adicionarEntrada.setMaximumSize(new java.awt.Dimension(150, 30));
        adicionarEntrada.setMinimumSize(new java.awt.Dimension(150, 30));
        adicionarEntrada.setPreferredSize(new java.awt.Dimension(150, 30));
        adicionarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarEntradaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 250, 0, 0);
        jPanel9.add(adicionarEntrada, gridBagConstraints);

        nomePaciente.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        nomePaciente.setText("Luis Claudio Da Silva Junior");
        nomePaciente.setToolTipText("");
        nomePaciente.setMaximumSize(new java.awt.Dimension(390, 20));
        nomePaciente.setMinimumSize(new java.awt.Dimension(390, 20));
        nomePaciente.setPreferredSize(new java.awt.Dimension(390, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel9.add(nomePaciente, gridBagConstraints);

        nSns.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        nSns.setText("12457845121");
        nSns.setMaximumSize(new java.awt.Dimension(100, 20));
        nSns.setMinimumSize(new java.awt.Dimension(100, 20));
        nSns.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 160);
        jPanel9.add(nSns, gridBagConstraints);

        contacto.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        contacto.setText("123456789");
        contacto.setMaximumSize(new java.awt.Dimension(100, 20));
        contacto.setMinimumSize(new java.awt.Dimension(100, 20));
        contacto.setPreferredSize(new java.awt.Dimension(100, 20));
        contacto.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 250);
        jPanel9.add(contacto, gridBagConstraints);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel9.add(jPanel2, gridBagConstraints);

        receitarMed.setBackground(new java.awt.Color(0, 132, 193));
        receitarMed.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        receitarMed.setForeground(new java.awt.Color(242, 242, 242));
        receitarMed.setText("Receitar");
        receitarMed.setMaximumSize(new java.awt.Dimension(150, 30));
        receitarMed.setMinimumSize(new java.awt.Dimension(150, 30));
        receitarMed.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 250, 0, 0);
        jPanel9.add(receitarMed, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel8.add(jPanel9, gridBagConstraints);

        jPanel10.setBackground(new java.awt.Color(0, 149, 218));
        jPanel10.setForeground(new java.awt.Color(0, 149, 218));
        jPanel10.setMaximumSize(new java.awt.Dimension(538, 4));
        jPanel10.setMinimumSize(new java.awt.Dimension(538, 4));
        jPanel10.setPreferredSize(new java.awt.Dimension(538, 4));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel8.add(jPanel10, gridBagConstraints);

        jPanel11.setMaximumSize(new java.awt.Dimension(538, 440));
        jPanel11.setMinimumSize(new java.awt.Dimension(538, 440));
        jPanel11.setPreferredSize(new java.awt.Dimension(538, 440));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setText("INFORMAÇÕES MÉDICAS");
        jLabel6.setMaximumSize(new java.awt.Dimension(212, 25));
        jLabel6.setMinimumSize(new java.awt.Dimension(212, 25));
        jLabel6.setPreferredSize(new java.awt.Dimension(212, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 300);
        jPanel11.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Alergias:");
        jLabel7.setMaximumSize(new java.awt.Dimension(140, 20));
        jLabel7.setMinimumSize(new java.awt.Dimension(140, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 100, 0);
        jPanel11.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Operações:");
        jLabel8.setMaximumSize(new java.awt.Dimension(140, 20));
        jLabel8.setMinimumSize(new java.awt.Dimension(140, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 100, 0);
        jPanel11.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Histórico de doenças:");
        jLabel9.setMaximumSize(new java.awt.Dimension(140, 20));
        jLabel9.setMinimumSize(new java.awt.Dimension(140, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 100, 0);
        jPanel11.add(jLabel9, gridBagConstraints);

        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setMinimumSize(new java.awt.Dimension(300, 120));
        jScrollPane5.setPreferredSize(new java.awt.Dimension(300, 120));

        alergiasList.setBackground(new java.awt.Color(242, 242, 242));
        alergiasList.setBorder(null);
        alergiasList.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        alergiasList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        alergiasList.setPreferredSize(new java.awt.Dimension(300, 120));
        jScrollPane5.setViewportView(alergiasList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 70);
        jPanel11.add(jScrollPane5, gridBagConstraints);

        jScrollPane6.setBorder(null);
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setMinimumSize(new java.awt.Dimension(300, 120));
        jScrollPane6.setPreferredSize(new java.awt.Dimension(300, 120));

        operacoesList.setBackground(new java.awt.Color(242, 242, 242));
        operacoesList.setBorder(null);
        operacoesList.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        operacoesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        operacoesList.setPreferredSize(new java.awt.Dimension(300, 120));
        jScrollPane6.setViewportView(operacoesList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 70);
        jPanel11.add(jScrollPane6, gridBagConstraints);

        jScrollPane7.setBorder(null);
        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setMinimumSize(new java.awt.Dimension(300, 120));
        jScrollPane7.setPreferredSize(new java.awt.Dimension(300, 120));

        histDoencasList.setBackground(new java.awt.Color(242, 242, 242));
        histDoencasList.setBorder(null);
        histDoencasList.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        histDoencasList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        histDoencasList.setPreferredSize(new java.awt.Dimension(300, 120));
        jScrollPane7.setViewportView(histDoencasList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 70);
        jPanel11.add(jScrollPane7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel8.add(jPanel11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jPanel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(0, 149, 218));
        jPanel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 60));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("MediFlow");
        jLabel1.setMaximumSize(new java.awt.Dimension(250, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(140, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 825);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1000);
        jPanel1.add(jLabel12, gridBagConstraints);

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        refreshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 1000, 0, 0);
        jPanel1.add(refreshButton, gridBagConstraints);

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarEntradaActionPerformed
        NovaEntradaRC novaEntrada = new NovaEntradaRC(consulta);
        novaEntrada.setVisible(true);
    }//GEN-LAST:event_adicionarEntradaActionPerformed

    private void refreshButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshButtonMouseClicked
        carregarEntradas(getClinica().obterRegistoPorSns(consulta.getSnsPaciente()).getEntradasRegistoClinico());
    }//GEN-LAST:event_refreshButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistoClinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistoClinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistoClinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistoClinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new RegistoClinico().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarEntrada;
    private javax.swing.JList<String> alergiasList;
    private javax.swing.JLabel contacto;
    private javax.swing.JPanel entradasPanel;
    private javax.swing.JScrollPane entradasScroll;
    private javax.swing.JList<String> histDoencasList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel nSns;
    private javax.swing.JLabel nomePaciente;
    private javax.swing.JList<String> operacoesList;
    private javax.swing.JButton receitarMed;
    private javax.swing.JLabel refreshButton;
    // End of variables declaration//GEN-END:variables
}
