/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inter.face;

import sql.server.SqlServer;

import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author rodri
 */
public class VistaDeLogin extends javax.swing.JFrame {

    /**
     * Creates new form VistaDeLogin
     */
    public VistaDeLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeUtilizador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        botaoLogin = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MediFLow");
        setName("login_panel"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(0, 149, 218));
        jPanel2.setPreferredSize(new java.awt.Dimension(720, 60));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("MediFlow");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 60));
        jLabel1.setMinimumSize(new java.awt.Dimension(140, 60));
        jLabel1.setPreferredSize(new java.awt.Dimension(140, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 520);
        jPanel2.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setMinimumSize(new java.awt.Dimension(640, 580));
        jPanel3.setPreferredSize(new java.awt.Dimension(720, 660));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 149, 218));
        jLabel2.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 149, 218));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nome de Utilizador");
        jLabel3.setMaximumSize(new java.awt.Dimension(250, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(250, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        nomeUtilizador.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        nomeUtilizador.setMinimumSize(new java.awt.Dimension(175, 30));
        nomeUtilizador.setPreferredSize(new java.awt.Dimension(200, 35));
        nomeUtilizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeUtilizadorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel3.add(nomeUtilizador, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 149, 218));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password");
        jLabel4.setMaximumSize(new java.awt.Dimension(250, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(250, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        jPanel3.add(jLabel4, gridBagConstraints);

        botaoLogin.setBackground(new java.awt.Color(0, 119, 174));
        botaoLogin.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        botaoLogin.setForeground(new java.awt.Color(245, 245, 245));
        botaoLogin.setText("Iniciar Sessão");
        botaoLogin.setMaximumSize(new java.awt.Dimension(200, 50));
        botaoLogin.setMinimumSize(new java.awt.Dimension(200, 50));
        botaoLogin.setPreferredSize(new java.awt.Dimension(225, 60));
        botaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 0);
        jPanel3.add(botaoLogin, gridBagConstraints);

        password.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        password.setMinimumSize(new java.awt.Dimension(175, 30));
        password.setPreferredSize(new java.awt.Dimension(200, 35));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 60, 0);
        jPanel3.add(password, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeUtilizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeUtilizadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeUtilizadorActionPerformed

    private void botaoLoginActionPerformed(java.awt.event.ActionEvent evt) {
        // Obtém o nome de utilizador e a palavra-passe inseridos pelo utilizador
        String utilizador = nomeUtilizador.getText();
        String senha = new String(password.getPassword());

        // Verifica se as credenciais são válidas
        if (verificarLogin(utilizador, senha)) {
            // Determina o tipo de utilizador com base no nome fornecido
            String tipoUtilizador = verificarTipoUtilizador(utilizador);

            if ("Funcionario".equalsIgnoreCase(tipoUtilizador)) {
                // Caso seja um funcionário, abre a vista correspondente
                VistaFuncionario vistaFuncionario = new VistaFuncionario();
                dispose(); // Fecha a janela de login
                vistaFuncionario.setVisible(true); // Mostra a nova janela
            } else if ("Gestor".equalsIgnoreCase(tipoUtilizador)) {
                // Caso seja um gestor, abre a vista correspondente
                VistaGestor vistaGestor = new VistaGestor();
                dispose(); // Fecha a janela de login
                vistaGestor.setVisible(true); // Mostra a nova janela
            } else if ("Medico".equalsIgnoreCase(tipoUtilizador)) {
                VistaMedico vistaMedico = new VistaMedico();
                dispose(); 
                vistaMedico.setVisible(true); 
            } else {
                // Caso o tipo de utilizador não seja reconhecido, mostra uma mensagem de erro
                JOptionPane.showMessageDialog(this, "Usuário não autorizado.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
           
        } else {
            // Se as credenciais forem inválidas, exibe uma mensagem de erro
            JOptionPane.showMessageDialog(this, "Credenciais incorretas. Tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean verificarLogin(String utilizador, String senha) {

        Connection conexao = SqlServer.DatabaseConnection.getInstance();// Obtém a conexão com a base de dados

        if (conexao != null) {  // Verifica se a conexão foi estabelecida com sucesso
            try {
                // Declara uma consulta SQL para verificar as credenciais
                String sql = "SELECT * FROM Utilizador WHERE Nome = ? AND Password = ?"; // Vai a tabela utilizador e verifica o Nome e a Password
                PreparedStatement statement = conexao.prepareStatement(sql);

                // Substitui os placeholders (?) pelos valores fornecidos pelo utilizador
                statement.setString(1, utilizador);
                statement.setString(2, senha);

                // Executa a consulta a base de dados e armazena o resultado
                ResultSet resultado = statement.executeQuery();

                // Retorna verdadeiro se encontrar um registo correspondente
                return resultado.next();
            } catch (SQLException e) { // Trata erros relacionados ao SQL
                System.out.println("Erro ao verificar as credenciais: " + e.getMessage());
            }
        } else {
            // Se a conexão não for estabelecida, exibe uma mensagem de erro
            System.out.println("Erro de conexão com o banco de dados.");
        }
        return false; // Retorna falso se a conexão falhar ou as credenciais forem inválidas
    }

    private String verificarTipoUtilizador(String utilizador) {

        Connection conexao = SqlServer.DatabaseConnection.getInstance(); // Obtém a conexão com a base de dados

        if (conexao != null) { // Verifica se a conexão foi estabelecida com sucesso
            try {
                // Consulta SQL para obter o ID do utilizador com base no nome
                String sqlId = "SELECT id FROM Utilizador WHERE nome = ?";
                PreparedStatement stmtId = conexao.prepareStatement(sqlId);
                stmtId.setString(1, utilizador);

                // Executa a consulta e armazena o resultado
                ResultSet rsId = stmtId.executeQuery();
                if (rsId.next()) { // Se encontrar um registo
                    int userId = rsId.getInt("id"); // Obtém o ID do utilizador

                    // Verifica se o ID corresponde a um funcionário
                    if (idExisteNaTabela(conexao, userId, "Funcionario", "ID_Funcionario")) {
                        return "Funcionario";
                    }

                    // Verifica se o ID corresponde a um gestor
                    if (idExisteNaTabela(conexao, userId, "Gestor", "ID_Gestor")) {
                        return "Gestor";
                    }

                    //Verifica se o ID corresponde a um medico
                    if (idExisteNaTabela(conexao, userId, "Medico", "ID_Medico")){
                    return "Medico";
                    }

                    // Adicionar mais verificações aqui para outros tipos de utilizadores, se necessário
                }
            } catch (SQLException e) { // Trata erros relacionados ao SQL
                System.out.println("Erro ao verificar o tipo de usuário: " + e.getMessage());
            }
        }

        return null; // Retorna null se não encontrar o tipo do utilizador
    }

    private boolean idExisteNaTabela(Connection conexao, int id, String tabela, String colunaId) {
        try {
            // Declara uma consulta SQL para verificar a existência do ID na tabela
            String sql = "SELECT " + colunaId + " FROM " + tabela + " WHERE " + colunaId + " = ?";
            PreparedStatement stmt = conexao.prepareStatement(sql);

            // Substitui o placeholder (?) pelo valor do ID
            stmt.setInt(1, id);

            // Executa a consulta e verifica se existe pelo menos um registo correspondente
            ResultSet rs = stmt.executeQuery();
            return rs.next(); // Retorna verdadeiro se encontrar um registo
        } catch (SQLException e) { // Trata erros relacionados ao SQL
            System.out.println("Erro ao verificar a tabela " + tabela + ": " + e.getMessage());
        }
        return false; // Retorna falso se ocorrer um erro ou não encontrar o ID
    }

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaDeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nomeUtilizador;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
