/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inter.face;
import javax.swing.*;
import sql.server.*;
import java.sql.*;
import java.util.*;
import medi.flow.Main;


/**
 *
 * @author draga
 */
public class VistaFuncionario extends javax.swing.JFrame {
    //ArrayList<> consultas = new ArrayList<Consulta>();
    /**
     * Creates new form VistaBase
     */
    public VistaFuncionario() {
        initComponents();
        carregarConsultasBaseDeDados();
    }

    void carregarConsultasBaseDeDados(){ //Carrega as consultas existentes de acordo com os dados fornecidos pelo SBGD
        /*Connection conexao = SqlServer.DatabaseConnection.getInstance(); //Abre a conexão com a base de dados
        int tamanhoPainelConsultas = 0;
        int nConsultas = 0; //Atributo responsavel por dizer quantos objetos do tipo consultaPanel existirão
        try{
            String contTuplos = "SELECT COUNT(*) FROM Consulta"; //Script para obter o numero de Tuplos da relação Consulta
            PreparedStatement statement = conexao.prepareStatement(contTuplos);
            ResultSet nTuplos = statement.executeQuery();

                if (nTuplos.next()) {
                    // Obtém o número de registros
                    nConsultas = nTuplos.getInt(1);
                }
        }catch ( SQLException e ){
            System.out.println("Erro ao encontrar a relação Consulta" + e.getMessage());
        }

        for (int i = 0; i < nConsultas; i++) {
            tamanhoPainelConsultas+=100; //aumenta o painel Pai em 100 (tamanho do painel Consulta)
            consultasPanel.setPreferredSize(new java.awt.Dimension(960, tamanhoPainelConsultas));
            criarPainelConsulta();
        }
         //Faz o scroll começar em cima
        SwingUtilities.invokeLater(() -> {
            JScrollBar verticalScrollBar = jScrollPane1.getVerticalScrollBar();
            verticalScrollBar.setValue(verticalScrollBar.getMinimum());
        });
        consultasPanel.revalidate();
        consultasPanel.repaint(); */
    }

    void criarPainelConsulta(){ //Adiciona uma consulta ao painel
        ConsultaFuncionario consulta = new ConsultaFuncionario();
        consultasPanel.add(consulta);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        botaoPesquisa = new javax.swing.JButton();
        barraPesquisa = new javax.swing.JTextField();
        botaoVerConsultas = new javax.swing.JButton();
        botaoMarcarConsultas = new javax.swing.JButton();
        marcarConsultas = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomePaciente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        contactoPaciente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nSns = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        motivoConsulta = new javax.swing.JTextArea();
        motivoConsulta.setLineWrap(true);
        motivoConsulta.setWrapStyleWord(true);
        jLabel8 = new javax.swing.JLabel();
        dataConsulta = new javax.swing.JFormattedTextField();
        botaoMarcar = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        horaConsulta = new javax.swing.JFormattedTextField();
        botaoDisponibilidade = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        idMedico = new javax.swing.JTextField();
        verConsultas = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultasPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 149, 218));
        jPanel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 60));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("MediFlow");
        jLabel1.setMaximumSize(new java.awt.Dimension(250, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(140, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 900);
        jPanel1.add(jLabel1, gridBagConstraints);

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        jPanel3.setMinimumSize(new java.awt.Dimension(1080, 660));
        jPanel3.setPreferredSize(new java.awt.Dimension(1080, 660));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel7.setBackground(new java.awt.Color(0, 149, 218));
        jPanel7.setPreferredSize(new java.awt.Dimension(960, 50));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        botaoPesquisa.setBackground(new java.awt.Color(0, 132, 193));
        botaoPesquisa.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        botaoPesquisa.setForeground(new java.awt.Color(245, 245, 245));
        botaoPesquisa.setText("PESQUISAR");
        botaoPesquisa.setMaximumSize(new java.awt.Dimension(120, 35));
        botaoPesquisa.setMinimumSize(new java.awt.Dimension(120, 35));
        botaoPesquisa.setPreferredSize(new java.awt.Dimension(140, 35));
        botaoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 80);
        jPanel7.add(botaoPesquisa, gridBagConstraints);

        barraPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        barraPesquisa.setText("Pesquisar...");
        barraPesquisa.setMinimumSize(new java.awt.Dimension(350, 35));
        barraPesquisa.setPreferredSize(new java.awt.Dimension(350, 35));
        barraPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraPesquisaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel7.add(barraPesquisa, gridBagConstraints);

        botaoVerConsultas.setBackground(new java.awt.Color(0, 132, 193));
        botaoVerConsultas.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        botaoVerConsultas.setForeground(new java.awt.Color(245, 245, 245));
        botaoVerConsultas.setText("Ver Consultas");
        botaoVerConsultas.setMaximumSize(new java.awt.Dimension(140, 35));
        botaoVerConsultas.setMinimumSize(new java.awt.Dimension(140, 35));
        botaoVerConsultas.setPreferredSize(new java.awt.Dimension(140, 35));
        botaoVerConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVerConsultasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel7.add(botaoVerConsultas, gridBagConstraints);

        botaoMarcarConsultas.setBackground(new java.awt.Color(0, 132, 193));
        botaoMarcarConsultas.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        botaoMarcarConsultas.setForeground(new java.awt.Color(245, 245, 245));
        botaoMarcarConsultas.setText("Marcar Consulta");
        botaoMarcarConsultas.setMaximumSize(new java.awt.Dimension(140, 35));
        botaoMarcarConsultas.setMinimumSize(new java.awt.Dimension(140, 35));
        botaoMarcarConsultas.setPreferredSize(new java.awt.Dimension(140, 35));
        botaoMarcarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMarcarConsultasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        jPanel7.add(botaoMarcarConsultas, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel3.add(jPanel7, gridBagConstraints);

        marcarConsultas.setBackground(new java.awt.Color(0, 149, 218));
        marcarConsultas.setMinimumSize(new java.awt.Dimension(960, 550));
        marcarConsultas.setOpaque(true);
        marcarConsultas.setVisible(false);
        marcarConsultas.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(0, 149, 218));
        jPanel2.setMinimumSize(new java.awt.Dimension(960, 550));
        jPanel2.setPreferredSize(new java.awt.Dimension(960, 550));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("DADOS DO PACIENTE");
        jLabel2.setMaximumSize(new java.awt.Dimension(450, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(450, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(450, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Nome Completo:");
        jLabel3.setMaximumSize(new java.awt.Dimension(450, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(450, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(450, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel3, gridBagConstraints);

        nomePaciente.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        nomePaciente.setMaximumSize(new java.awt.Dimension(450, 30));
        nomePaciente.setMinimumSize(new java.awt.Dimension(450, 30));
        nomePaciente.setPreferredSize(new java.awt.Dimension(450, 30));
        nomePaciente.setRequestFocusEnabled(false);
        nomePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePacienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(nomePaciente, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("N.º SNS:");
        jLabel4.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(200, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 250);
        jPanel2.add(jLabel4, gridBagConstraints);

        contactoPaciente.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        contactoPaciente.setMaximumSize(new java.awt.Dimension(200, 30));
        contactoPaciente.setMinimumSize(new java.awt.Dimension(200, 30));
        contactoPaciente.setPreferredSize(new java.awt.Dimension(200, 30));
        contactoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactoPacienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 250, 0, 0);
        jPanel2.add(contactoPaciente, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Contacto:");
        jLabel5.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(200, 30));
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 250, 0, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        nSns.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        nSns.setMaximumSize(new java.awt.Dimension(200, 30));
        nSns.setMinimumSize(new java.awt.Dimension(200, 30));
        nSns.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 250);
        jPanel2.add(nSns, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("DADOS DA CONSULTA");
        jLabel6.setMaximumSize(new java.awt.Dimension(450, 30));
        jLabel6.setMinimumSize(new java.awt.Dimension(450, 30));
        jLabel6.setPreferredSize(new java.awt.Dimension(450, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Motivo:");
        jLabel7.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel7.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 300);
        jPanel2.add(jLabel7, gridBagConstraints);

        motivoConsulta.setColumns(20);
        motivoConsulta.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        motivoConsulta.setRows(5);
        motivoConsulta.setMinimumSize(new java.awt.Dimension(300, 200));
        motivoConsulta.setPreferredSize(new java.awt.Dimension(450, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        jPanel2.add(motivoConsulta, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Data:");
        jLabel8.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel8.setMinimumSize(new java.awt.Dimension(200, 30));
        jLabel8.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 250);
        jPanel2.add(jLabel8, gridBagConstraints);

        dataConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        dataConsulta.setMaximumSize(new java.awt.Dimension(200, 30));
        dataConsulta.setMinimumSize(new java.awt.Dimension(200, 30));
        dataConsulta.setPreferredSize(new java.awt.Dimension(200, 30));
        dataConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataConsultaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 250);
        jPanel2.add(dataConsulta, gridBagConstraints);

        botaoMarcar.setBackground(new java.awt.Color(0, 132, 193));
        botaoMarcar.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        botaoMarcar.setForeground(new java.awt.Color(242, 242, 242));
        botaoMarcar.setText("MARCAR");
        botaoMarcar.setMaximumSize(new java.awt.Dimension(150, 35));
        botaoMarcar.setMinimumSize(new java.awt.Dimension(150, 35));
        botaoMarcar.setPreferredSize(new java.awt.Dimension(150, 35));
        botaoMarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMarcarConsultasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        jPanel2.add(botaoMarcar, gridBagConstraints);

        label.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        label.setForeground(new java.awt.Color(242, 242, 242));
        label.setText("Hora:");
        label.setMaximumSize(new java.awt.Dimension(200, 30));
        label.setMinimumSize(new java.awt.Dimension(200, 30));
        label.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 250, 0, 0);
        jPanel2.add(label, gridBagConstraints);

        horaConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        horaConsulta.setMaximumSize(new java.awt.Dimension(200, 30));
        horaConsulta.setMinimumSize(new java.awt.Dimension(200, 30));
        horaConsulta.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(0, 250, 0, 0);
        jPanel2.add(horaConsulta, gridBagConstraints);

        botaoDisponibilidade.setBackground(new java.awt.Color(0, 132, 193));
        botaoDisponibilidade.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        botaoDisponibilidade.setForeground(new java.awt.Color(242, 242, 242));
        botaoDisponibilidade.setText("DISPONIBILIDADE ");
        botaoDisponibilidade.setMaximumSize(new java.awt.Dimension(150, 35));
        botaoDisponibilidade.setMinimumSize(new java.awt.Dimension(150, 35));
        botaoDisponibilidade.setPreferredSize(new java.awt.Dimension(150, 35));
        botaoDisponibilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDisponibilidadeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        jPanel2.add(botaoDisponibilidade, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("ID do Médico:");
        jLabel9.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel9.setMinimumSize(new java.awt.Dimension(200, 30));
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 350);
        jPanel2.add(jLabel9, gridBagConstraints);

        idMedico.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        idMedico.setMaximumSize(new java.awt.Dimension(200, 30));
        idMedico.setMinimumSize(new java.awt.Dimension(200, 30));
        idMedico.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 50);
        jPanel2.add(idMedico, gridBagConstraints);

        marcarConsultas.add(jPanel2, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(marcarConsultas, gridBagConstraints);

        verConsultas.setBackground(new java.awt.Color(0, 149, 218));
        verConsultas.setMinimumSize(new java.awt.Dimension(960, 35));
        verConsultas.setOpaque(true);
        verConsultas.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(960, 550));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(960, 550));

        consultasPanel.setMinimumSize(new java.awt.Dimension(900, 0));
        consultasPanel.setPreferredSize(new java.awt.Dimension(900, 0));
        consultasPanel.setLayout(new java.awt.GridLayout(0, 1, 10, 10));
        jScrollPane1.setViewportView(consultasPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        verConsultas.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(verConsultas, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void barraPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraPesquisaActionPerformed

    private void botaoVerConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVerConsultasActionPerformed


        if (verConsultas.isVisible() == false){
            barraPesquisa.setVisible(true);
            botaoPesquisa.setVisible(true);
            verConsultas.setVisible(true);
            marcarConsultas.setVisible(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_botaoVerConsultasActionPerformed

    private void botaoMarcarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMarcarConsultasActionPerformed
        if (marcarConsultas.isVisible() == false){
            barraPesquisa.setVisible(false);
            botaoPesquisa.setVisible(false);
            marcarConsultas.setVisible(true);
            verConsultas.setVisible(false);
            nomePaciente.setText("");
            contactoPaciente.setText("");
            nSns.setText("");
            motivoConsulta.setText("");
            dataConsulta.setText("");
            horaConsulta.setText("");
            idMedico.setText("");
        } // TODO add your handling code here:
    }//GEN-LAST:event_botaoMarcarConsultasActionPerformed

    private void botaoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisaActionPerformed

    }//GEN-LAST:event_botaoPesquisaActionPerformed

    private void nomePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePacienteActionPerformed

    private void dataConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataConsultaActionPerformed

    private void contactoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactoPacienteActionPerformed

    private void botaoDisponibilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDisponibilidadeActionPerformed
        DisponibilidadeMedicos disp = new DisponibilidadeMedicos();
        disp.setVisible(true);
    }//GEN-LAST:event_botaoDisponibilidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraPesquisa;
    private javax.swing.JButton botaoDisponibilidade;
    private javax.swing.JButton botaoMarcar;
    private javax.swing.JButton botaoMarcarConsultas;
    private javax.swing.JButton botaoPesquisa;
    private javax.swing.JButton botaoVerConsultas;
    private javax.swing.JPanel consultasPanel;
    private javax.swing.JTextField contactoPaciente;
    private javax.swing.JFormattedTextField dataConsulta;
    private javax.swing.JFormattedTextField horaConsulta;
    private javax.swing.JTextField idMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JLayeredPane marcarConsultas;
    private javax.swing.JTextArea motivoConsulta;
    private javax.swing.JTextField nSns;
    private javax.swing.JTextField nomePaciente;
    private javax.swing.JLayeredPane verConsultas;
    // End of variables declaration//GEN-END:variables
}
