/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inter.face;

import sql.server.*;
import javax.swing.*;
import java.awt.*;
import java.text.ParseException;


/**
 *
 * @author rodri
 */
// Classe que representa a vista de login
public class VistaDeLogin extends javax.swing.JFrame {
    /**
     * Creates new form VistaDeLogin
     */
    // Construtor da classe
    public VistaDeLogin() {
        initComponents(); // Inicializa os componentes da interface gráfica
        addKeyListenerToComponents(this.getContentPane());// Adiciona um keyListener a todos os componentes da janela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeUtilizador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        botaoLogin = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MediFLow");
        setName("login_panel"); // NOI18N
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(0, 149, 218));
        jPanel2.setPreferredSize(new java.awt.Dimension(720, 60));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("MediFlow");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 60));
        jLabel1.setMinimumSize(new java.awt.Dimension(140, 60));
        jLabel1.setPreferredSize(new java.awt.Dimension(140, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 430);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel5.setToolTipText("");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 640);
        jPanel2.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setMinimumSize(new java.awt.Dimension(640, 580));
        jPanel3.setPreferredSize(new java.awt.Dimension(720, 660));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 149, 218));
        jLabel2.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 149, 218));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ID de Utilizador");
        jLabel3.setMaximumSize(new java.awt.Dimension(250, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(250, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        nomeUtilizador.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        nomeUtilizador.setMinimumSize(new java.awt.Dimension(175, 30));
        nomeUtilizador.setPreferredSize(new java.awt.Dimension(200, 35));
        nomeUtilizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeUtilizadorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel3.add(nomeUtilizador, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 149, 218));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password");
        jLabel4.setMaximumSize(new java.awt.Dimension(250, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(250, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        jPanel3.add(jLabel4, gridBagConstraints);

        botaoLogin.setBackground(new java.awt.Color(0, 119, 174));
        botaoLogin.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        botaoLogin.setForeground(new java.awt.Color(245, 245, 245));
        botaoLogin.setText("Iniciar Sessão");
        botaoLogin.setMaximumSize(new java.awt.Dimension(200, 50));
        botaoLogin.setMinimumSize(new java.awt.Dimension(200, 50));
        botaoLogin.setPreferredSize(new java.awt.Dimension(225, 60));
        botaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 0);
        jPanel3.add(botaoLogin, gridBagConstraints);

        password.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        password.setMinimumSize(new java.awt.Dimension(175, 30));
        password.setPreferredSize(new java.awt.Dimension(200, 35));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 60, 0);
        jPanel3.add(password, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Método para verificar login ao clicar no botão
    private void nomeUtilizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeUtilizadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeUtilizadorActionPerformed


    // Ação para verificar login ao clicar no botão
    private void botaoLoginActionPerformed(java.awt.event.ActionEvent evt) {
        // Obtém o nome de utilizador e a palavra-passe inseridos pelo utilizador
        String utilizador = nomeUtilizador.getText();// Obtém o nome de utilizador inserido pelo utilizador
        String password = new String(this.password.getPassword());// Obtém a palavra-passe inserida pelo utilizador

        int idMedico;// ID do médico
        String passwordGestor;// Palavra-passe do gestor

        // Verifica se as credenciais são válidas
        String tipoUtilizador = SqlGeral.verificarLogin(utilizador, password);// Verifica se as credenciais são válidas
        try {// Tenta abrir a vista correspondente ao tipo de utilizador
            switch (tipoUtilizador) {// Verifica o tipo de utilizador
                case "Gestor":// Caso seja um gestor
                    passwordGestor = password;// Obtém a palavra-passe do gestor
                    // Abre a vista de administrador
                    new VistaGestor(passwordGestor).setVisible(true);
                    this.dispose();
                    break;
                case "Médico":// Caso seja um médico
                    // Define o ID do médico antes de abrir a vista
                    idMedico = Integer.parseInt(utilizador);
                    // Abre a vista de médico
                    VistaMedico vistaMedico = new VistaMedico(idMedico);
                    vistaMedico.setVisible(true);
                    this.dispose();
                    break;
                case "Secretaria":// Caso seja uma secretária
                    // Abre a vista de secretaria
                    new VistaSecretaria().setVisible(true);
                    this.dispose();
                    break;
                default:// Caso as credenciais sejam inválidas
                    // Mostra uma mensagem de erro
                    JOptionPane.showMessageDialog(this, "Credenciais inválidas. Tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);// Mostra uma mensagem de erro
                    break;
            }
        } catch (NumberFormatException | HeadlessException | NullPointerException e) {// Caso ocorra um erro
            JOptionPane.showMessageDialog(this, "Credenciais inválidas. Tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);// Mostra uma mensagem de erro
        } catch (ParseException e) {// Caso ocorra um erro
            throw new RuntimeException(e);// Lança uma exceção
        }
    }

    // Ação para verificar login ao clicar no botão
    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    // Adiciona um keyListener a todos os componentes da janela
    private void addKeyListenerToComponents(java.awt.Container container) {
        // Percorre todos os componentes do conteiner passado como parametro
        for (java.awt.Component component : container.getComponents()) {
            // Adiciona um keyListener para capturar eventos de tecla pressionada
            component.addKeyListener(new java.awt.event.KeyAdapter() {
                @Override
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    formKeyPressed(evt);
                }
            });
            if (component instanceof java.awt.Container) {// Se o componente for um container
                addKeyListenerToComponents((java.awt.Container) component);// Adiciona um keyListener a todos os componentes do container
            }
        }
    }
    // Método para verificar login ao pressionar a tecla Enter
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {// Se a tecla pressionada for Enter
            botaoLogin.doClick();// Simula um clique no botão de login
        }// TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    // Método main
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VistaDeLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nomeUtilizador;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
